services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: indexer
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
